feat: warn with dinodollars at Ralph
kolmafia/kolmafia pull request #1001
Opened 2022-08-20 15:18 UTC by midgleyc

Not sure whether the dinodollars go away, or the shop goes away, or the shop contents don't go away, but I think warning is a good idea if that's right.

The shop is `whichshop=dino`, though.

2022-08-20 16:16 UTC, gausie commented
The problem with this is that there's nothing really to spend them on that isn't also a quest item, unless you have hundreds

2022-08-20 18:37 UTC, midgleyc commented
You could grab some DNAde for the basement, or the shirts for a low-shiny account combat rate adjustment?

2022-08-20 23:33 UTC, Veracity0 requested changes

2022-08-20 23:33 UTC, Veracity0 commented on src/net/sourceforge/kolmafia/request/RelayRequest.java
> +    if (KoLCharacter.inDinocore()) {
How about some tests in RelayRequestWarningsRequestTest?
RelayRequest.sendBreakPrismWarning has a warning for leaving Robocore for a similar reason.
No tests for Kingdom of Exploathing and Plumber paths, alas. for 

That whole file could used some @Nested classes - and Cleanups.

2022-08-21 17:18 UTC, Veracity0 approved these changes

2022-08-21 18:27 UTC, merged