Add cartography tracking
kolmafia/kolmafia pull request #1098
Opened 2022-09-18 23:42 UTC by libraryaddict

2022-09-19 08:55 UTC, midgleyc requested changes
I prefer the other choice for names you gave in your initial post, because it contains the actual zone the adventure occurs at.

Other than that looks good, thanks!

2022-09-19 09:58 UTC, gausie commented
> The other choice for names I had was
> 
> ```
> user    lastCartographyHauntedBilliards    -1
> user    lastCartographyGuanoJunction    -1
> user    lastCartographyDarkNeck    -1
> user    lastCartographyDefiledNook    -1
> user    lastCartographyBooPeak    -1
> user    lastCartographyCastleTop    -1
> user    lastCartographyZeppelinProtesters    -1
> user    lastCartographyFratHouse    -1
> user    lastCartographyFratHouseVerge    -1
> user    lastCartographyHippyCampVerge    -1
> ```

These are better than what you chose. I'd even consider location lastCartography<snarfblat> purely for scripting, but acknowledge that is annoying in other contexts

2022-09-20 07:46 UTC, midgleyc approved these changes

2022-09-20 12:13 UTC, gausie approved these changes

2022-09-20 12:14 UTC, merged