Cache encoded preference values.
kolmafia/kolmafia pull request #1275
Opened 2022-11-12 19:28 UTC by phulin

Each call to set a property results in writing all of the preferences out to disk, if `saveSettingsOnSet` is enabled. To my knowledge, this is the default and most users keep it enabled. This can take up a substantial amount of CPU runtime (say 10-15% in my unrepresentative profiling tests), as the properties need to all be encoded using `encodeString` each update.

This PR caches the encoded lines for each property, if `saveSettingsOnSet` is enabled. This means that only the changed property has to be re-encoded, rather than every single property. Saving the preferences to file then becomes a simple concatenation of the cached encoded lines. Because the encoded values are stored in a TreeMap, we can also get rid of the sorting I added when moving the main map to a ConcurrentHashMap.

The following microbenchmark runs in 78 seconds without this PR and 8.8 seconds with it - a roughly 9x speedup. I did not observe any speed change when `saveSettingsOnSet` was off.
```java
  @Test
  public void speed() {
    Preferences.setBoolean("saveSettingsOnSet", true);
    Preferences.saveSettingsToFile = true;
    long start = 0;
    ThreadMXBean threadMXBean = ManagementFactory.getThreadMXBean();
    var keySet = new ArrayList<>(Preferences.getMap(false, true).keySet());
    long threadId = Thread.currentThread().getId();
    for (int i = -2; i < 8; i++) {
      if (i == 0) start = threadMXBean.getThreadCpuTime(threadId);
      for (var pref : keySet) {
        Preferences.setString(pref, "abc" + i);
      }
    }
    long end = threadMXBean.getThreadCpuTime(threadId);
    System.out.println("Elapsed: " + (end - start) / 1_000_000);
  }
```

2022-11-12 20:12 UTC, phulin commented
This test is passing locally. Something must be different about file paths on github. I'm not quite sure what the issue is - any ideas?

2022-11-13 10:02 UTC, midgleyc requested changes
Some comments requesting clarification; I can help look into the test thing.

2022-11-13 10:27 UTC, midgleyc commented
The tests fail for me locally too: the preferences file is always blank.

2022-11-13 10:32 UTC, midgleyc commented
Found the issue: the username wants to be lowercase. You're presumably on a case-insensitive file system?

2022-11-13 13:45 UTC, phulin reviewed
Thanks much for the help.

2022-11-13 13:45 UTC, phulin commented on src/net/sourceforge/kolmafia/preferences/Preferences.java
> +    if (name == "saveSettingsOnSet" && (boolean) object) {
Encoded values are initialized in `putUser` as values are loaded. I'll rename this "reinitialize" to be more descriptive and add a comment.

2022-11-13 13:45 UTC, phulin commented on src/net/sourceforge/kolmafia/preferences/Preferences.java
> +  private static void initializeEncodedValues() {
👍

2022-11-13 16:31 UTC, midgleyc approved these changes

2022-11-13 18:11 UTC, merged