refactor: convert boolean modifiers to enum
kolmafia/kolmafia pull request #1458
Opened 2023-01-22 22:13 UTC by midgleyc

Added some tests for potentially dangerous areas, but I think the coverage is pretty good. It caught a couple of issues, at least!

2023-01-22 23:01 UTC, Veracity0 requested changes
Love this work. Can hardly wait until bitmaps are no longer indexes into array.

2023-01-23 08:28 UTC, midgleyc commented on src/net/sourceforge/kolmafia/Modifiers.java
> +    for (int index = 1; index < this.bitmaps.length; ++index) {
yes, I was planning to do everything at once. For now it just skips writing into the first index.

2023-01-23 15:04 UTC, Veracity0 requested changes

2023-01-23 15:10 UTC, midgleyc commented on src/net/sourceforge/kolmafia/Modifiers.java
> +  public static final Set<BooleanModifier> BOOLEAN_MODIFIERS =
I think I had that originally but it gives a compile error as `Modifiers` needs `BooleanModifiers`, but `BooleanModifiers` needs `Modifiers`, so it's a circular dependency.

2023-01-23 15:42 UTC, midgleyc commented on src/net/sourceforge/kolmafia/Modifiers.java
> +  public static final Set<BooleanModifier> BOOLEAN_MODIFIERS =
Managed to get it to work after all. Must have been doing something wrong.

2023-01-23 15:48 UTC, Veracity0 commented on src/net/sourceforge/kolmafia/Modifiers.java
> +  public static final Set<BooleanModifier> BOOLEAN_MODIFIERS =
What I mean is, move the declaration of BOOLEAN_MODIFIERS from Modifiers to BooleanModifier.
BooleanModifiers need not import Modifiers; it has its own variable.

Like this:

BooleanModifiers.java:
```
  public static final Set<BooleanModifier> BOOLEAN_MODIFIERS =
      Collections.unmodifiableSet(EnumSet.allOf(BooleanModifier.class));
```
Modifiers.java:
```
import net.sourceforge.kolmafia.modifiers.BooleanModifier;
...
public static final Set<BooleanModifier> BOOLEAN_MODIFIERS = BooleanModifier.BOOLEAN_MODIFIERS;
```

or even:
```
import net.sourceforge.kolmafia.modifiers.BooleanModifier;
import net.sourceforge.kolmafia.modifiers.BooleanModifier.BOOLEAN_MODIFIERS;
```

2023-01-23 15:56 UTC, Veracity0 approved these changes

2023-01-23 16:03 UTC, Veracity0 commented on src/net/sourceforge/kolmafia/Modifiers.java
> +  public static final Set<BooleanModifier> BOOLEAN_MODIFIERS =
Yes. That is even better. You had to change a few additional files, but it is nice and clean.

2023-01-23 16:12 UTC, merged