All currently existing sources of Eldritch Tentacles are free encounters.
kolmafia/kolmafia pull request #1590
Opened 2023-03-01 17:23 UTC by Malibu-Stacey

As title.

2023-03-01 18:59 UTC, midgleyc commented
Thanks!

You've not quite got the syntax right -- it's a space, not a tab, after free -- but I'll fix it up and add a couple more omitted free monsters.

2023-03-01 19:08 UTC, midgleyc requested changes
Okay, so I can't fix it because I don't have permissions to push to your repo. But if you could make the following monsters free:
* lynyrd
* %monster%
* the Tunnel of L.O.V.E. enemies
* the Cargo Cultist Shorts bell fights
* Sssshhsssblllrrggghsssssggggrrgglsssshhssslblgl

That would be nice.

Autoscend also says that Travoltron, the Peripatetic Pasta and the wandering accordionists are free, so maybe those too?

2023-03-01 19:08 UTC, midgleyc commented on src/data/monsters.txt
> +Eldritch Tentacle	1974	eldtentacle.gif	FREE	Scale: 7 Cap: 400 Floor: 20 Init: -10000 P: horror Phys: 50 Elem: 50 E: spooky Article: an	eldritch effluvium (0)	eldritch effluvium (0)	eldritch effluvium
```suggestion
Eldritch Tentacle	1974	eldtentacle.gif	FREE Scale: 7 Cap: 400 Floor: 20 Init: -10000 P: horror Phys: 50 Elem: 50 E: spooky Article: an	eldritch effluvium (0)	eldritch effluvium (0)	eldritch effluvium (0)
```

2023-03-01 23:29 UTC, Malibu-Stacey commented
> Okay, so I can't fix it because I don't have permissions to push to your repo. But if you could make the following monsters free:

That's bizarre, there's no permission changes since the last PR.

> * lynyrd
> * %monster%
> * the Tunnel of L.O.V.E. enemies
> * the Cargo Cultist Shorts bell fights
> * Sssshhsssblllrrggghsssssggggrrgglsssshhssslblgl
> 
> That would be nice.

Can do!

> Autoscend also says that Travoltron, the Peripatetic Pasta and the wandering accordionists are free, so maybe those too?

I think it's wrong about Travoltron but I'll double check in the game itself after rollover when the account I use to test autoscend is done with its current run. The others are ancient revamp wanderers which I don't think there's any way to fight now anyway.

2023-03-02 09:44 UTC, midgleyc requested changes

2023-03-02 09:44 UTC, midgleyc commented on src/data/monsters.txt
> +lynyrd	1533	FREE lynyrd.gif	Atk: 150 Def: 150 HP: 155 Init: 10000 P: beast Article: a	lynyrd skin (100)
```suggestion
lynyrd	1533	lynyrd.gif	FREE Atk: 150 Def: 150 HP: 155 Init: 10000 P: beast Article: a	lynyrd skin (100)
```

2023-03-02 18:26 UTC, Malibu-Stacey commented
Confirming Travoltron costs an adventure to kill. autoscend is definitely wrong about that one. At 15 advs before the fight I cleavered it to death in the relay browser and had 14 advs afterwards and no message in the GCLI of "This combat did not cost a turn".

2023-03-02 18:29 UTC, Malibu-Stacey commented
> It might be because this one is from your `main` branch?

The CBB consumables one was on my main branch too. I haven't created any branches in my fork ever. I'm blaming GitHub for being weird.

2023-03-02 19:33 UTC, midgleyc approved these changes
Thanks!

2023-03-02 19:34 UTC, merged