refactor: drop rate storage
kolmafia/kolmafia pull request #1660
Opened 2023-04-04 13:58 UTC by midgleyc

Adjust monster drop code. Previously, item drop rates were stored in an AdventureResult by putting both drops and flags into the "count" field. Extract these into a proper object.

This allows for fractional drop rates. KoL drop rates can be fractional: this is used either for conditional rares below 1%, or Dreadsylvanian rares, which are sub-1% but not conditional (as in, there is no roll to check whether you get the item: they still can't be YRed).

Make the behaviour for unknown drop rates explicit: they get a flag of 0 iff they have no other flag already.

There were some references to a flag of "b". This used to be "bounty".

Move to using a regex to validate the items + drops: this finds one issue.

Change `item_drops` to return a float[item]. I don't know how much trouble this will cause. It looks like the usages I can find don't assign it to a variable but just loop over the returned value.

2023-04-04 14:16 UTC, gausie commented
This is a great change and enabling fractional droprates is huge! Thank you

2023-04-05 12:10 UTC, Veracity0 requested changes

2023-04-05 12:23 UTC, midgleyc commented on test/net/sourceforge/kolmafia/AreaCombatDataTest.java
> +        var iceHotel = AdventureDatabase.getAreaCombatData("The \"Fun\" House");
thanks

2023-04-05 12:24 UTC, midgleyc commented
Added some tests. For AreaCombatData, the pickpocket-only bowtie being 5.0 instead of 5 was true before this change. I kept it as it was.

2023-04-05 12:55 UTC, Veracity0 approved these changes

2023-04-05 13:58 UTC, merged