feat: add loathingidol command
kolmafia/kolmafia pull request #1745
Opened 2023-06-03 10:52 UTC by midgleyc

I was hoping that if you had "satisfy with coinmasters" it would say "acquire a loathing idol microphone & loathingidol WHATEVER" but it doesn't.

Still, this is good enough for me.

2023-06-03 19:24 UTC, Veracity0 requested changes

2023-06-03 19:24 UTC, Veracity0 commented on src/net/sourceforge/kolmafia/textui/command/LoathingIdolCommand.java
> +    UseItemRequest useBoomBox = UseItemRequest.getInstance(item);
useMicrophone?

2023-06-03 20:51 UTC, midgleyc commented on src/net/sourceforge/kolmafia/textui/command/LoathingIdolCommand.java
> +    UseItemRequest useBoomBox = UseItemRequest.getInstance(item);
yes, whoops

2023-06-03 21:06 UTC, Veracity0 approved these changes

2023-06-03 21:16 UTC, merged

2023-06-08 04:03 UTC, Shiverwarp commented
This seems to work great, the only problem is Mafia doesn't recognize that the microphone is consumed in the process, so need to refresh inventory between each command