Derive TCRS from spaded seeding
kolmafia/kolmafia pull request #1767
Opened 2023-06-13 18:28 UTC by gausie

I should really put this here rather than have it living as it has done for a fair few months in my own fork of mafia. The spading was done by @phulin and myself and it was really fun to slowly eke out!

The thing that's left really is just the delicate process of shifting over to this new system completely. It also needs thoughts on a testing strategy, of which I would love to hear yours. This has also been merged against latest and with all the great changes to modifiers I have logically migrated but have not tested.

I am very low on time at the moment as I am getting married on Sunday... and am becoming a father 5 weeks later, at which point I will have less time. So for all those reasons I'm unlikely to get this sorted any time soon, though those 5 weeks aren't *totally* busy!

2023-06-13 20:11 UTC, Veracity0 commented
I think this is glorious, and I would enjoy contributing to it, assuming I have commit access.

I just finished day 2 of my first (of 6) LoL runs, and I have documentation and tweaks for a few of my scripts in the immediate future, but I'm keen to see this implemented/deployed, and I'll be studying - and testing, and discussing - it by and by.

2023-07-24 15:40 UTC, Veracity0 commented
I finished my ascensions and ping testing, so, I'm ready to look at this now.
I did a conflict resolution merge, and then fixed it. :)
Tests still fail.

Looking forward to seeing what you've done, here.

2023-07-26 14:05 UTC, Veracity0 commented
I see that you've added "drink" to a bunch of things that you can't actually drink; KoL has them marked as booze, but if you attempt to drink them, it gives a cute message and doesn't actually consume them.

We have a consumption type - USE_MESSAGE_DISPLAY which was originally created so that we could pop up a little window to show the cute messages for "using" certain items. It was a primary usage, not a secondary usage or attribute. Marking 11 drinks as  "drink, message" is cute - and if you actually have to submit inv_drink to "use" it, it is appropriate - but there is no code to handle "message" as a secondary usage.

Looking a little deeper, the only place which displays the message has this:
```
      case USE_MESSAGE_DISPLAY:
        if (!Preferences.getBoolean("suppressNegativeStatusPopup")) {
          UseItemRequest.showItemUsage(showHTML, responseText);
        }
        return;
```
The property is not in defaults.txt.
In the OptionsFrame, it says "Suppress popup dialog for items which cause harmful effects".

Huh?

Well, this little "message display" feature - which I think I added in 2006 or so - apparently no longer works as originally intended. Somebody decided to add an undocumented property to disable it entirely. And the original implementation ALSO popped up a window when you "used" a familiar hatchling, since that also has a cute message, and you can only do it once ever per familiar. Apparently, that annoyed some people, so that popup is commented out. (The net result is that whenever I use a new familiar hatchling, I always grow it in the browser so I can see and enjoy the message. Heck. Why wasn't THAT put under a preference?)

Well, this comment is rather a digression from the actual point of this PR, but it caught my eye that you were extending this (old) feature.

Is it because the non-consumable drinks are assigned different "sizes" - like all drinks - in TCRS?

2023-07-26 14:24 UTC, gausie commented
Thank you for the upkeep, V. That really helps. I am going to turn my attention to this very soon.

And yes - we need to maintain the fact that they are drinks for various rolls that are done differently in that case. I think naming also differs for drinks. I'll have to add "message" as a secondary attribute.

And huh that's not good. I bet @Rinn knows something about this, as our resident person-who-runs-mafia-headless and as such doesn't like dialogue boxes.

2023-07-26 16:09 UTC, Veracity0 commented
This was the PR from a year and a half ago. I did not see it go in; it got lumped in with a Language Server PR in the Recent GitHub Changes. I've inquired about it. In particular, the motivation. Was there a bug report?

I think that if you are headless, we should obviously not pop up a window. I expect the "message" feature should simply not work, in this case. We COULD extract the HTML from the responseText and print it, but nah.

https://github.com/kolmafia/kolmafia/pull/501

2023-07-26 16:24 UTC, gausie commented
Looks like I approved the PR!

On Wed, 26 Jul 2023, 17:09 Veracity0, ***@***.***> wrote:

> This was the PR from a year and a half ago. I did not see it go in; it got
> lumped in with a Language Server PR in the Recent GitHub Changes. I've
> inquired about it. In particular, the motivation. Was there a bug report?
>
> I think that if you are headless, we should obviously not pop up a window.
> I expect the "message" feature should simply not work, in this case. We
> COULD extract the HTML from the responseText and print it, but nah.
>
> #501 <https://github.com/kolmafia/kolmafia/pull/501>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kolmafia/kolmafia/pull/1767#issuecomment-1652117107>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABL4LXBGTWRWLL4ZVLCBVDXSE6MHANCNFSM6AAAAAAZFI3754>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-26 16:27 UTC, Rinn commented
Yeah it's not a huge deal. It'd be cool if a browser dialog could appear if in the relay browser but it's not important enough to me to spend any time on. The biggest issue I have in the relay browser is it's very difficult to manually halt script execution, running `abort` in the relay cli doesn't usually work.

2023-07-27 12:15 UTC, Veracity0 commented
OK, I understand the current scope of this.

KoLmafia has extensive TCRS support. I implemented it. :)

For each class/zodiac combo, we have a (three) data files:
```
TCRS_<class>_<zodiac>.txt
TCRS_<class>_<zodiac>_cafe_booze.txt
TCRS_<class>_<zodiac>_cafe_food.txt
```
If you are in TCRS, we load these at login and override consumable sizes and object enchantments.
On logout, we remove the overrides.
We also allow you to "derive" those overrides and "save" them, in case we are missing data or have wrong info.
Currently, you have to be in a specific TCRS run to "derive" the data, since we have to look at the item descriptions and parse the names and enchantments.

This PR, in its current state, lets you "guess" enchantments via algorithm, rather than "derive" via item desc.
Conceptually, the single public method - TCRSDatabase.deriveItem - is replaced by TCRSDatabase.guessItem.
(TCRSDatabase.guessPotion is also currently public, although it should not be; it is called only by guessItem.)

What are the ultimate plans?

- We still have the TCRS data files and load and override at login? deriving (guessing) on demand would be very hard to deal with. Also, there are people who depend on our data files. (There is an idiot on the KoL forums who asked people to derive a file for him because he refuses to run KoLmafia, even to simply type the four commands needed to just do it for himself. Nobody says he has to do literally anything else in KoLmafia, but, no.)
- You don't need to be logged in to TCRS to "guess" a data file. That would be very handy, should we need to augment those files or re-generate them, if KoL changes a seed. Do we add the "tcrs guess" command or replace "tcrs derive"? As mentioned, allow that to be done whether or not you are logged in to a particular TCRS run.
- What about the cafe food and booze? Those are not "items". They have pseudo "cafe" food and booze numbers, which we can see from the item description file names.

Testing. I like your "guessAll" function. There is a general issue I have with how Junit handles test like this. Which is to say, I'd like it if it could report all errors it finds, rather than stopping on the first error it sees. I fixed DataFileTest to do that, so I could find all the places you used "message" as a secondary type - and so it would actually print the item at fault, rather than depending on "assertThat" to print extra info - which it does not do, the way testing is configured on our project.

Well, perhaps the errors would be too verbose that way, and it's simpler to just fix the errors one at a time, for this project.

2023-07-27 14:25 UTC, gausie commented
My eventual plan was to remove the data files and rename guess -> derive. Possibly adding/renaming some existing code to check our derivations from observable info. It's an odd thing to work on in many ways because I want to test against the datafiles and in order to do so have to maintain the code built for parsing them!

As always I can be entirely swayed by your opinion here, of course.

>     * We still have the TCRS data files and load and override at login? deriving (guessing) on demand would be very hard to deal with. 

Would it? I figure we load it into memory in the same way we load the data files into memory. This is what KoL does internally. Or better yet we derive each item on demand and cache the result.

> Also, there are people who depend on our data files. (There is an idiot on the KoL forums who asked people to derive a file for him because he refuses to run KoLmafia, even to simply type the four commands needed to just do it for himself. Nobody says he has to do literally anything else in KoLmafia, but, no.)

I think that if we really care about this we could perhaps add a new build command that generates these files and hosts them somewhere.

>     * What about the cafe food and booze? Those are not "items". They have pseudo "cafe" food and booze numbers, which we can see from the item description file names.

I'm not sure if @phulin and I actually got round to spading these - that may need some time.

> I fixed DataFileTest to do that, so I could find all the places you used "message" as a secondary type - and so it would actually print the item at fault, rather than depending on "assertThat" to print extra info - which it does not do, the way testing is configured on our project.

Thank you for doing so. The due date for my (as yet still in utero) first baby was 4 days ago so I've been really preoccupied with supporting my wife and will become yet more preoccupied in the coming weeks/months, so I can't put a time scale on further work here for now

2023-07-27 16:08 UTC, Veracity0 commented
Congrats on your marriage and your imminent baby. My youngest is 29, and, like all offspring, brought both joy and frustration. The joy won out in the end. :) 

On demand seems tricky. It would include everything on the booze/food/spleen/potions panel that you either have (acquirable) access to or can create. So, first time you open the item manager, do a whole bunch of derivation? And when you get a new ingredient, derive everything you can now make?

Perhaps easier to derive everything when you log in. Faster or slower than reading a file?

We'll see.

2023-07-28 17:32 UTC, Veracity0 requested changes, later dismissed

2023-07-28 17:32 UTC, Veracity0 commented on src/data/items.txt
> +#	beverage, potion, avatar
I see that you add BEVERAGE to the usage comments in fullness.txt, but do not actually mark anything as a "beverage".

2023-07-28 17:32 UTC, Veracity0 commented on src/data/items.txt
> +2092	antique hand mirror	443142276	handmirror.gif	usable, combat	t,d	100
This does not seem to be true.

2024-06-14 03:01 UTC, Veracity0 commented
It's been a year since you opened this.
Any progress? L)

2024-06-14 11:11 UTC, gausie commented
Nope! I shall close this until I can get back to it.

2025-06-07 16:28 UTC, midgleyc commented
I have merged main and updated the branch to compile. The immediate issues are:
* the "spooky powder overflows and so has its original effect" thing doesn't work at all
* when generating names, the effects aren't include in the name (e.g. a +fam weight item should have "friendly" in the name but does not)
* some other effects are wrong

2025-06-07 16:31 UTC, gausie commented
I think there are some item types we never finished spading for name generation

2025-06-10 16:31 UTC, midgleyc commented
okay, so potions do work after all, the issue was in the test: it doesn't use the local TCRS files but instead gets them from GitHub, and they leak between tests.

Not sure what the actual fix is for that -- they're in data/ which doesn't seem accessible.

The leak has also revealed that there are many more modifiers we need to copy across -- e.g. McHugeLarge.

2025-06-10 18:59 UTC, gausie commented
> okay, so potions do work after all, the issue was in the test: it doesn't use the local TCRS files but instead gets them from GitHub, and they leak between tests.
> 
> Not sure what the actual fix is for that -- they're in data/ which doesn't seem accessible.
> 
> The leak has also revealed that there are many more modifiers we need to copy across -- e.g. McHugeLarge.

Thank you for working this out! Are you planning on doing anything on this? I can definitely pick up from here but as I've said elsewhere recently I have a lot less free time so can't guarantee any specific timings. If you are going to be doing something let me know so I don't step on toes.

2025-06-10 21:13 UTC, midgleyc commented
On the file issue: I don't know how to solve this so if you have any ideas go ahead!

On the copyable modifiers: I don't know exactly which ones want copying. Ideally I think I'd have a char in TCRS to check some. Especially ideally I'd have a dev account to check the RPN ;)

I'm not sure of the mechanics, but I think a baseline would be the modifiers without a descPattern: I presume Brimstone, Cloathing, Synergies, McHugeLarge still apply bonuses. Then there's thorns / damage aura which I suspect aren't RPN and so stick around (or are they blanked?)

Then there's stuff like Great Wolf's beastly trousers, which has 3 enchants, which implies the "troubling vulnerability" is one enchant instead of the 5 we have it as, assuming I understand how this works.

2025-06-11 11:54 UTC, jaadams5 commented
> okay, so potions do work after all, the issue was in the test: it doesn't use the local TCRS files but instead gets them from GitHub, and they leak between tests.
> 
> Not sure what the actual fix is for that -- they're in data/ which doesn't seem accessible.
> 

Is it worth  "fixing" the tests (or will that be OBE once this work is finished)?  If I understand the issue I would be interested in fixing it.  I seem to be behind a couple of cases where a test has to work around "mafia files".

2025-06-11 11:57 UTC, gausie commented
The tests will be removed as a final step of this PR, insofaras we will no
longer have the need to test reading the data files and will trust our
generated modifiers over those we find in said files.

On Wed, Jun 11, 2025 at 12:54 Jamie Adams ***@***.***> wrote:

> *jaadams5* left a comment (kolmafia/kolmafia#1767)
> <https://github.com/kolmafia/kolmafia/pull/1767#issuecomment-2962390851>
>
> okay, so potions do work after all, the issue was in the test: it doesn't
> use the local TCRS files but instead gets them from GitHub, and they leak
> between tests.
>
> Not sure what the actual fix is for that -- they're in data/ which doesn't
> seem accessible.
>
> Is it worth "fixing" the tests (or will that be OBE once this work is
> finished)? If I understand the issue I would be interested in fixing it. I
> seem to be behind a couple of cases where a test has to work around "mafia
> files".
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kolmafia/kolmafia/pull/1767#issuecomment-2962390851>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABL4LQDMAENO7PV35C2NYT3DAKHTAVCNFSM6AAAAAB62B6LUOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDSNRSGM4TAOBVGE>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2025-06-11 22:54 UTC, Veracity0 commented
I am glad you are working again on this. I did all the original TCRS support - including generating the data files for sign/class pairs (and the JS support in Valhalla to let you see what you get for astral consumables.)
It will be nice to automatically derive this stuff.

2025-06-12 10:21 UTC, gausie commented
Ok I have fixed the file loading issue that Ryo mentioned, I think. We now do not download new files and refer exclusively to the local data files (which I have copied over to `/src/data/TCRS for now. As Ryo mentioned to me in a private message, we will need to keep the files in `/data/TCRS` for some time as people move over to the new system.

2025-12-08 22:25 UTC, midgleyc commented
I was looking at some stuff related to this.

In order to calculate the TCRS enchants, we need to know how many enchants the base item has, and whether or not they're RPN enchants. Some will need a manual override (e.g. tiki lighter has two TCRS enchants and one visible enchant, with the other presumably being the stat distribution; sometimes items like the cursed blanket have no enchants for unclear reasons).

Excluding this, we want to:
* separate the innate shield DR and the enchantment-added DR, because the innate DR is constant and not an enchant
* create some "original modifiers": "both regen", "all stats", "prismatic damage", "all resistance". Each of these counts as one enchant, but is expanded by Mafia (to HP / MP regen, muscle / myst / mox, all 5 elemental damages, all 5 elemental resistances).

2026-08-03 19:18 UTC, gausie commented
I'm going to use an LLM to split out some of the stuff that can be merged now from this PR and isolate specifically the bit that we haven't nailed down yet (i.e. merge data stuff, keep seeding stuff).

2026-08-03 19:45 UTC, midgleyc commented
If you keep the existing TCRS data generation stuff you can merge most of TCRSDatabase and the tests that check hardcoded potions.

You can't merge the whole thing because e.g. we don't get equipment names right because we don't know the ordering (and the modifier count issue).

2026-08-06 07:58 UTC, midgleyc commented on src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
> +        "Hot Damage: +5, Cold Damage: +5, Spooky Damage: +5, Stench Damage: +5, Sleaze Damage: +5"),
this one is interesting because we can determine it (e.g. see pair of plants): the order is spooky-stench-hot-cold-sleaze

2026-08-06 07:59 UTC, midgleyc commented on src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
> +        "of regeneration", "HP Regen Min: 3, HP Regen Max: 5, MP Regen Min: 3, MP Regen Max: 5")
this one also has a different message in the enchant (e.g. "Regenerate 5-10 HP and MP per adventure") so we can determine this one too

2026-08-06 17:52 UTC, gausie commented on src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
> +        "of regeneration", "HP Regen Min: 3, HP Regen Max: 5, MP Regen Min: 3, MP Regen Max: 5")
Honestly this stuff is guesswork on my end, but that is super interesting.

2026-08-11 12:51 UTC, midgleyc commented
Okay, issue: `enchantCount` is returning the enchantment count of items *in TCRS*, probably because we load TCRS data after setting ourselves the class and path in the `guessAll` test. So moving the shield DR out hasn't improved things because we're reading the TCRS enchantment count, not the actual enchantment count. Sort of marking our own homework.

Similarly for potions -- the "pass-through" effect is the effect in TCRS, which is always necessarily correct.

2026-08-20 23:02 UTC, gausie commented
We have a checkmark(!)

2026-08-21 20:03 UTC, gausie commented on src/data/tcrs.txt
> +RPN Modifier	Accessory Drop
This needs to not live here of course

2026-08-26 03:42 UTC, gausie commented
Folks this is ready for review!

2026-08-26 08:40 UTC, midgleyc commented on src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
> +    // shuffle
some comments are messed up like this one, by spotless. Can you join the next line?

2026-08-26 08:42 UTC, midgleyc commented on src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
> +      mods.addModifier("Effect", quoted(effectName));
I think "quoted" should be handled on ModifierList, and the way it should work is that if the modifier is a string modifier, the value should be quoted.

I don't know how it works elsewhere, though, and if other callers pass in the name quoted better to be consistent.

2026-08-26 08:44 UTC, Rinn commented on test/net/sourceforge/kolmafia/persistence/TCRSDatabaseTest.java
> +      // MODIFIERS / EVALUATED_MODIFIERS are meta-fields holding the whole (order-sensitive)
generally could you have the comments like this cleaned up so they don't feel as generated (line character limit, weird line breaks, odd prose etc)

2026-08-26 08:45 UTC, midgleyc commented
Also, have you run derive again and confirmed it's consistent?

What will be the procedure for someone running TCRS in the future / scripts to use this?

2026-08-26 08:55 UTC, midgleyc commented on src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
> +   * Shuffles the cosmetic adjectives with the given glibc stream and joins them into a name prefix.
"glibc stream" is nonsense?

Also the rest of the comment is good in-progress notes and not necessary now.

2026-08-26 13:24 UTC, gausie commented on test/net/sourceforge/kolmafia/persistence/TCRSDatabaseTest.java
> +      // MODIFIERS / EVALUATED_MODIFIERS are meta-fields holding the whole (order-sensitive)
I thought I got them all!

2026-08-26 13:45 UTC, gausie commented on src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
> +   * Shuffles the cosmetic adjectives with the given glibc stream and joins them into a name prefix.
glibc stream is the stream of numbers generated by php's rand() (which uses glibc's random instead of mersenne-twister)

2026-08-26 13:46 UTC, gausie commented
> Also, have you run derive again and confirmed it's consistent?

Yes. I also made a tool for people to re-derive without direct access to the multi army here: https://tcrs.loathers.net/. I was going to host on kolmafia's org but then I need to work out hosting.

> What will be the procedure for someone running TCRS in the future / scripts to use this?

What do you mean?

2026-08-26 14:58 UTC, midgleyc commented on src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
> +   * Shuffles the cosmetic adjectives with the given glibc stream and joins them into a name prefix.
interesting, but thanks for replacing it anyway

2026-08-26 15:02 UTC, midgleyc commented on src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
> +        // TCRS effects are limited to those available when the path (Tiki Temerity) launched
Tiki Temerity is not the path

so either
> TCRS effects are limited to those available when the path launched (Tiki Temerity)

or
> TCRS effects are limited to those available (Tiki Temerity) when the path launched

if you really don't want the effect at the end

2026-08-26 15:05 UTC, midgleyc commented
> What do you mean?

Suppose somebody wants to run a scripted ascension in TCRS, and there have been new consumables added that aren't in Mafia's data files.

At the moment, they run `tcrs derive` at the start of the ascension to populate the internal database (or whatever they're supposed to do). Post-this PR, we can automatically generate item data: does that happen automatically or does the user need to do something?

2026-08-26 15:16 UTC, gausie commented
> > What do you mean?
> 
> Suppose somebody wants to run a scripted ascension in TCRS, and there have been new consumables added that aren't in Mafia's data files.
> 
> At the moment, they run `tcrs derive` at the start of the ascension to populate the internal database (or whatever they're supposed to do). Post-this PR, we can automatically generate item data: does that happen automatically or does the user need to do something?

The item data will be automatically derived, but it will be slightly wrong until we add the data that mafia can't add from automatic item introspection (e.g. enchantment count being off, and a bunch of other things). I can make it automatically derive items that are not in items.txt instead of guess them, maybe.

2026-08-26 17:27 UTC, gausie commented
Ok I have implemented that (and actually wired this spading to the modifiers we use). I decided to take the dive and rename the old "derive" to "introspect" and then my "guess" to "derive". It will be confusing when reviewing but is less confusing to future readers.

2026-08-27 08:22 UTC, midgleyc commented on .github/workflows/check.yml
> +          name: tcrs-guessAll-mismatches-${{ matrix.os }}
guessAll -> deriveAll

2026-08-27 08:25 UTC, midgleyc commented on src/data/cultshorts.txt
> +70	Candy	Dweeby (40)	The Strength...  of the Future (20)
I've bug reported it and it would be nice for CDM to fix this ;)

2026-08-27 08:26 UTC, midgleyc commented on src/data/modifiers.txt
>  # Dinsey mascot mask: Changes Your Avatar
probably worth making this an actual modifier given it occurs on three items and would fix the counts. on main + regenerate etc.

2026-08-27 08:28 UTC, midgleyc commented on src/data/modifiers.txt
> +Item	Goggles of Loathing	Initiative: +50, Hot Resistance: +5, Initiative Penalty: [10*env(underwater)], Item Drop Penalty: [10*env(underwater)], Meat Drop Penalty: [10*env(underwater)], Cloathing, Fa
this triple penalty is "makes you a better diver" and feels like it should be detectable.

2026-08-27 08:29 UTC, midgleyc commented on src/data/modifiers.txt
> +Item	nurse's hat	Maximum HP: +300, HP Regen Min: 30, HP Regen Max: 60, MP Regen Min: 10, MP Regen Max: 15, Familiar Effect: "atk", Enchantment Count: 3
why is this not being detected as 3 already?

2026-08-27 08:31 UTC, midgleyc commented on src/data/modifiers.txt
>  # The Sagittarian's leisure pants: Disco Bandit Combat Skills weaken enemies by an additional 20%
this is used by 5 items and could be a real modifier

2026-08-27 08:33 UTC, midgleyc commented on src/data/modifiers.txt
> +Item	candy cane sword cane	Weapon Damage Percent: +50, Never Fumble, Rollover Effect: "Sugar Rush", Rollover Effect Duration: 250, Weapon Damage: [5+5*pref(_surprisinglySweetStabUsed)+5*pref(_surpris
why are we miscounting this one?

2026-08-27 08:35 UTC, midgleyc commented on src/data/modifiers.txt
>  # Rain-Doh yellow laser gun: Super Accurate!
super accurate is used by 2 items, but I'm not really inclined to make it a modifier, as we don't know what it does (and there's yet another +hit bonus on the legendary pasta wand)

2026-08-27 08:36 UTC, midgleyc commented on src/data/modifiers.txt
> +Item	Staff of the Staff of Life	Spell Damage Percent: +50, Maximum HP: +30, MP Regen Min: 5, MP Regen Max: 6, HP Regen Min: 10, HP Regen Max: 12, Jiggle: "Full HP Recovery", Enchantment Count: 4
again, why do we miscount this? the HP / MP regen amounts are different

2026-08-27 08:47 UTC, midgleyc commented on src/data/modifiers.txt
>  # mirrored aviator shades: Kill 10% More Skeletons
while it will never come back, kill x% more skeletons is on two items

2026-08-27 08:55 UTC, midgleyc commented on src/net/sourceforge/kolmafia/modifiers/BooleanModifier.java
> +          BLIND,
given blind is on 4 items and counts for 2 and doesn't count for 2 I would be tempted to leave it off

2026-08-27 08:56 UTC, midgleyc commented on src/net/sourceforge/kolmafia/persistence/ConsumablesDatabase.java
> +    DECENT("decent", null),
given the numbers were removed this can just be left as "decent"

2026-08-27 09:05 UTC, midgleyc commented
okay so from observation the modifiers:
* Changes Your Avatar
* Disco Bandit Combat Skills weaken enemies by an additional X%
* Super Accurate!
* Kill X% More Skeletons

are used by multiple items and worth adding to main to improve our enchant count guesses.

Maybe not "Changes Your Avatar" in retrospect, it's not present on some items that change your avatar like "invisible bag" so it might just be confusing.

2026-08-27 12:03 UTC, midgleyc commented on src/data/cultshorts.txt
> +70	Candy	Dweeby (40)	The Strength...  of the Future (20)
<img width="1021" height="153" alt="image" src="https://github.com/user-attachments/assets/725ebc38-4781-4926-bae2-889239553e37" />
It was fixed.

2026-08-27 17:08 UTC, gausie commented on src/data/modifiers.txt
>  # Rain-Doh yellow laser gun: Super Accurate!
It seems you decided to do it regardless!

2026-08-27 17:14 UTC, gausie commented on src/data/modifiers.txt
> +Item	candy cane sword cane	Weapon Damage Percent: +50, Never Fumble, Rollover Effect: "Sugar Rush", Rollover Effect Duration: 250, Weapon Damage: [5+5*pref(_surprisinglySweetStabUsed)+5*pref(_surpris
The majority of enchantments that are dependent on a pref don't seem to be RPN, so I filter it out.

2026-08-28 01:11 UTC, gausie commented on src/data/modifiers.txt
> +Item	Goggles of Loathing	Initiative: +50, Hot Resistance: +5, Initiative Penalty: [10*env(underwater)], Item Drop Penalty: [10*env(underwater)], Meat Drop Penalty: [10*env(underwater)], Cloathing, Fa
I agree, I added a test that goes red if your counted enchantments === your Enchantment Count, so if we sort this in future we will be forced to come back to this.

2026-08-28 07:59 UTC, midgleyc commented on src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
> +  /**
we shouldn't have two docstrings for the same function. The top docstring seems to want to apply to the function below this one.

2026-08-28 08:17 UTC, midgleyc commented on src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
> +    if (id == ItemPool.QUANTUM_TACO
as ZERO_ADVENTURE_CONSUMABLES gets it own set with one item, these should too

I think having the special cases as separate sets makes things more visible

2026-08-28 08:17 UTC, midgleyc commented on src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
> +    if (id == ItemPool.GUNPOWDER_BURRITO || id == ItemPool.BEERY_BLOOD) {
same here, pull out to a set

2026-08-28 08:18 UTC, midgleyc commented on src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
> +          Map.entry(ItemPool.SKULL_CRIMBOWEEN_COOKIE, 256), // Bells in the Batfry
EffectPool for the numbers.

2026-08-28 08:20 UTC, midgleyc commented on src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
> +  // TODO: replace this token sniff with ModifierExpression parsing and Modifier enum lookups.
planning on doing this TODO or leaving it?

2026-08-28 08:38 UTC, midgleyc commented on src/net/sourceforge/kolmafia/session/ResultProcessor.java
> +    // The Strength... of the Future
remove comment

2026-08-28 08:38 UTC, midgleyc commented on src/net/sourceforge/kolmafia/session/ResultProcessor.java
>      // The Strength... of the Future
also remove this line, for reference

2026-08-28 08:40 UTC, midgleyc commented on test/net/sourceforge/kolmafia/persistence/TCRSDatabaseTest.java
> +        java.nio.file.Path.of(System.getProperty("user.dir"))
loose fully qualified path

2026-08-28 14:51 UTC, gausie commented on test/net/sourceforge/kolmafia/persistence/TCRSDatabaseTest.java
> +        java.nio.file.Path.of(System.getProperty("user.dir"))
It's because we already have Path coming in from AscensionPath.Path and I didn't want to expand all of those just to shorten this.

2026-08-28 15:09 UTC, gausie commented on src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
> +  // TODO: replace this token sniff with ModifierExpression parsing and Modifier enum lookups.
I am going to do half of it I think. Coming now

2026-08-28 17:28 UTC, midgleyc commented on test/net/sourceforge/kolmafia/persistence/TCRSDatabaseTest.java
> +        java.nio.file.Path.of(System.getProperty("user.dir"))
"import x as y" would be really convenient for Java to have eh?

2026-08-28 17:30 UTC, midgleyc submitted a review, later dismissed
Thanks!

What a long strange trip it's been...

2026-08-29 15:43 UTC, gausie commented
I was just running some TCRS turns and I think there are a few wiring things to sort out.

2026-08-29 16:36 UTC, gausie commented
Haha ok this issue is that I've forgotten to spade the cafe modifiers. I bet it's just the same as everything else. Will get that sorted this week. The quest continues...

2026-08-30 00:08 UTC, gausie commented
Confirmed working, did some maximizing and some adventuring and all looks great.

2026-08-30 08:59 UTC, midgleyc approved these changes

2026-08-30 20:52 UTC, merged