ASH record equality
kolmafia/kolmafia pull request #1895
Opened 2023-08-12 17:39 UTC by Veracity0

Rather than ASH believing that every record value is equal to any other record value, provide "shallow" equality testing:

1) Must be the same record type
2) All non-composite fields must be identical
3) Field which are, themselves, records must have record-equality
4) Aggregate fields must have the same size.
We do not do a "deep" comparison of aggregate values.

2023-08-12 17:53 UTC, Veracity0 commented
Fucking windows.

My test script - and expected output - includes the '≈' operator, which is "approximately equal" or "ignore case".
That's a perfectly good UTF-8 character, but, not for Windows, it seems.

2023-08-12 22:00 UTC, heeheehee-kolmafia requested changes
Other than the handful of violations of antisymmetry (which is important since you're implementing the Comparable interface), this looks reasonable.

(While you say that you're only implementing equality, I don't see any mechanism that prevents someone from trying to order two records, either in existing code or introduced by this PR.)

2023-08-12 22:03 UTC, heeheehee-kolmafia commented
I suspect the "proper" way to deal with "Windows is using the wrong file encoding for loaded text files" is to set

```	systemProperty 'file.encoding', 'UTF-8'
```
in the test stanza in build.gradle.

2023-08-13 13:51 UTC, Veracity0 commented
Yes. What I really want is equality. Value implements Comparable, but for composites, that is difficult and, in general, not useful. I can envision certain records where a total ordering makes sense. Our "sort" operation, for reordering arrays based on the the values of (fields of) the keys, lets the user specify something to that effect. ASH allows you to define ```string to_string(RECORD)``` and s```tring to_string(TYPEDEF)``` - and those are found and applied, as appropriate, when coercing values to strings. But there is no user-overridable way to specify ordering.

I'm going to do the following:

1) Operator.compareValues calls compareTo or compareToIgnoreCase. For ==, !=, or ≈, call equals or equalsIgnoreCase.
For other comparison operators, call compareTo or compareToIgnoreCase.
2) AggregateValue overrides the equality methods for shallow equality.
3) RecordValue overrides the equality operators and checks that for each field, as defined by its type.
4) The Parser allows equality comparisons for all types, but other comparisons only for simple types.

End result is that Value implements Comparable, but non-primitive data types (which don't override generic Value's compareTo) will get whatever that method provides - but there will be no ASH syntax that will actually invoke it for such values.

2023-08-13 13:56 UTC, Veracity0 commented
Regarding the "≈" operator, I sort of regret implementing it. As applied only to strings, it could have been a function - but since ASH lets you use "==" for strings, rather than requiring ```.equals()``` it seemed distasteful. Also, I thought that we could come up with a definition for floats - except the user would want control over the epsilon, we assume, so, perhaps not.

It has the disadvantage that it is not easy to type. Especially, perhaps, in Windows, as the test failure might indicate.

Almost APL-ish. :)

2023-08-13 14:26 UTC, heeheehee-kolmafia commented
> I'm going to do the following:
> 
>     1. Operator.compareValues calls compareTo or compareToIgnoreCase. For ==, !=, or ≈, call equals or equalsIgnoreCase.
>        For other comparison operators, call compareTo or compareToIgnoreCase.
> 
>     2. AggregateValue overrides the equality methods for shallow equality.
> 
>     3. RecordValue overrides the equality operators and checks that for each field, as defined by its type.
> 
>     4. The Parser allows equality comparisons for all types, but other comparisons only for simple types.
> 
> 
> End result is that Value implements Comparable, but non-primitive data types (which don't override generic Value's compareTo) will get whatever that method provides - but there will be no ASH syntax that will actually invoke it for such values.

This is reasonable. Do note, though: you're potentially running into a situation where .compareTo() will no longer be consistent with .equals().

2023-08-13 16:34 UTC, Veracity0 commented
I am making CompositeValue (an abstract class) require subclasses to implement ```boolean equals(Object o, boolean ignoreCase)```. Given that, ```CompositeValue.compareTo(Value o, boolean ignoreCase)``` will check for equality (and return 0) first and then defer to the superclass if it is not equal - which will give something which is not useful, but which will be consistent.

2023-08-13 16:44 UTC, Veracity0 commented on src/net/sourceforge/kolmafia/textui/parsetree/RecordValue.java
> +    if (!type.equals(orv.getRecordType())) {
RecordValue no longer implements compareTo.

2023-08-13 16:45 UTC, Veracity0 commented on src/net/sourceforge/kolmafia/textui/parsetree/RecordValue.java
> +          return -1;
RecordValue no longer implements compareTo.
AggregateValue now implements equals() and this code is there now.

2023-08-13 16:46 UTC, Veracity0 commented
Next up is to the Parser work I mentioned and also try out the build.gradle tweak to see if I can re-enable my original test.

2023-08-13 19:27 UTC, heeheehee-kolmafia commented
> which will give something which is not useful, but which will be consistent.

When I say inconsistent, I mean that there are cases where x.compareTo(y) == 0 does not yield true in exactly the same situations as x.equals(y).

It seems to me that Value.compareTo() will fall back to comparing contentLong in this case, which will ~always be equal for aggregates. The main consequence that you've noted is that arbitrary records are considered equal to each other.

A simple option that is _nearly_ consistent is to use System.identityHashCode(x) - System.identityHashCode(y) which is similarly useless and is only inconsistent when we have a hash collision.

2023-08-13 19:31 UTC, heeheehee-kolmafia approved these changes
That said -- I think this is good enough to merge as-is, since it addresses the issue you're trying to fix.

It may be useful to leave a comment how this technically violates Comparable's contract in case we run into problems with this down the line.

2023-08-13 21:01 UTC, Veracity0 commented
I now understand how this could show up in (what should be) invalid code.

```RECORD == INT``` will go to RecordValue's ```equals``` method, but the reverse goes to Value's.

For '<', it goes to CompositeValue's ```compareTo```, but the reverse goes to Value's.

If I make the Parser allow equality operators iff both lhs and rhs are CompositeValues, the "reverse" cases will be compile errors.

And if I make the Parser allow only equality comparisons, then the compareTo cases will be moot.

That said, perhaps Value.compareTo could throw a ClassCast error if rhs is a CompositeValue - and CompositeValue.compareTo could do the same if rhs is NOT such.

I think the Parser changes could go in a followup PR since, as you say, this one does what I want if you use == on two record values.

2023-08-14 01:07 UTC, heeheehee-kolmafia commented
Right. This is no worse for the status quo, other than the bit where it will cause surprising results for things like `sort` that assume compareTo() generates a total ordering.

2023-08-14 01:38 UTC, merged