Remove unused preferences.
kolmafia/kolmafia pull request #979
Opened 2022-08-13 02:20 UTC by heeheehee-kolmafia

These were identified to have no references elsewhere in the codebase.

I manually took a pass to further filter this set down (removing things like HC vs SC breakfast, choice adventures, PvP season prefs, etc).

Would be good to have a second set of eyes to double-check that I didn't make any mistakes here.

2022-08-13 04:05 UTC, Veracity0 approved these changes
It would be nice if there was a technique such that removing a property from defaults.txt would also remove it from preferences.

I wrote a script which would generate a list of all properties not in default.txt and let me decide which ones were from scripts and which from dead properties.

If you can come up with a method to facilitate this, cool.

I am not expecting not.

2022-08-13 04:51 UTC, gausie requested changes
https://github.com/kolmafia/kolmafia/blob/e58cf2bcc7fae7c5d34675ae2ed27ad676a0e017/src/net/sourceforge/kolmafia/session/ResultProcessor.java#L320

Keep the bird a day mod prefs please!

2022-08-13 04:53 UTC, gausie commented
Also umiversalSeasoningAvailable is composed

https://github.com/kolmafia/kolmafia/blob/fbfd2252d01c76a8b52d01d14a8f23573646e162/src/net/sourceforge/kolmafia/request/SwaggerShopRequest.java#L70

2022-08-13 05:01 UTC, Veracity0 commented
> Also universalSeasoningAvailable is composed

Seems to be true.

2022-08-13 11:58 UTC, jaadams5 commented
> I wrote a script which would generate a list of all properties not in default.txt and let me decide which ones were from scripts and which from dead properties.

I seem to recall doing something similar but I think I used awk and access to source code so perhaps yours is the better candidate for publication than mine :-)

zarqon has some similar capability in PrefRefPlus.

2022-08-16 02:39 UTC, heeheehee-kolmafia commented
> https://github.com/kolmafia/kolmafia/blob/e58cf2bcc7fae7c5d34675ae2ed27ad676a0e017/src/net/sourceforge/kolmafia/session/ResultProcessor.java#L320
> 
> Keep the bird a day mod prefs please!

Done. Same with universalSeasoningAvailable.

2022-08-16 02:57 UTC, Veracity0 approved these changes

2022-08-16 02:57 UTC, Veracity0 commented on src/data/defaults.txt
> -user	lastEasterEggBalloon	-1
This KoL change is a tragedy. :-(

2022-08-16 17:10 UTC, merged