feat: add the simple wishable dinos
kolmafia/kolmafia pull request #998
Opened 2022-08-19 18:43 UTC by midgleyc

The simple dinosaurs, while monster modifiers in-path, are also wishable separately. They have 0 stats and die instantly without ML.

2022-08-19 18:55 UTC, Veracity0 requested changes

2022-08-19 18:55 UTC, Veracity0 commented on src/data/monsters.txt
> +
According to [Tokoeka](https://kolmafia.us/members/tokoeka.4856/)

2230 - kachungasaur, dino_kachung.gif

2022-08-19 22:56 UTC, Veracity0 approved these changes

2022-08-20 13:42 UTC, gausie approved these changes

2022-08-20 14:02 UTC, merged